name: Sample
on:
  pull_request: null
  push:
    branches:
    - main
jobs:
  run:
    name: Run Sample code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup Elm
      uses: jorelali/setup-elm@v3
      with:
        elm-version: 0.19.1
    - name: Install elm-format
      run: npm install -g elm-format

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: stack-1-${{ hashFiles('svg2elm/package.yaml') }}-${{ hashFiles('svg2elm/stack.yaml.lock') }}
        restore-keys: |
          stack-1-
    - uses: haskell/actions/setup@v2
      name: Setup Haskell
      with:
        ghc-version: 9.2.5
        enable-stack: true
        stack-version: 'latest'

    - name: Clone primer/octicons
      run: git clone --depth=1 -bv$(cat .octicons-version) https://github.com/primer/octicons.git
    - name: Generate Elm code from SVG
      env:
        STACK_BUILD_OPTS: --system-ghc
      run: ./script/svg2elm.sh

    - name: Build Sample
      run: elm make --optimize --output=../docs/index.html src/Main.elm 
      working-directory: sample

    - name: Check diff
      run: |
        git add -N .
        git diff --exit-code

    - name: Generate Elm docs
      run: elm make --docs=docs.json
